name: my_environment
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - numpy=1.24.3
  - pandas=2.0.3
  - nltk=3.9.1
  - spacy=3.7.2
  - scikit-learn=1.3.2
  - xgboost=2.1.1
  - lightgbm=4.5.0
  - imbalanced-learn=0.12.3
  - transformers=4.32.1
  - tqdm=4.66.5
  - joblib=1.4.2
  - tensorflow=2.10.0
  - pytorch=2.4.1
  - torchvision=0.20.0
  - torchaudio=2.4.1
  - pytorch-cuda=12.4
  - beautifulsoup4=4.12.3
  - scipy=1.10.1
  - datasets=3.0.2
  - flask=3.0.3
  - tabulate=0.9.0 
  - pip
  - pip:
      - matplotlib==3.7.5
      - seaborn==0.13.2
      - wordcloud==1.9.3
      - contractions==0.1.73
      - optuna==4.0.0
      - pyspellchecker==0.8.1
      - datasets==3.0.2 --upgrade
      - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0.tar.gz